### ISSUE TITLE
Spam at xevil.com homepage

### ISSUE THREAD

**Issue by denilsonsa** [lvella/xevil#5]
Hello! Do you own the https://www.xevil.com/ website?

Because [since August 2018](https://web.archive.org/web/20180827214209/http://www.xevil.com/) it includes some links to some casino thing. The text and the link(s) changed over time. AFAIK, [this](https://web.archive.org/web/20180808024655/http://www.xevil.com/) was the last clean version.

**Comment by lvella** [comment]
No, I am not the owner.
